---

skip_list:
  - 'var-naming'
  - 'no-handler'
  - '503'  # no-handler code
  - 'role-name'
  - '106'
  - 'ignore-errors'
  - 'yaml'
  - '204'  # line length => checked by yamllint
  - 'galaxy[no-changelog]'  # requires inline documentation of modules
  - 'meta-unsupported-ansible'  # support for older installations from apt and so on
