---

namespace: 'ansibleguy'
name: 'opnsense'
version: 1.0.20
readme: 'README.md'
authors:
  - 'AnsibleGuy <guy@ansibleguy.net>'
description: "Ansible Collection to manage OPNSense firewalls using its API's"
license_file: 'LICENSE.txt'
tags:
  - 'firewall'
  - 'api'
  - 'opnsense'
  - 'iac'
dependencies: {}
repository: 'https://github.com/ansibleguy/collection_opnsense'
documentation: 'https://opnsense.ansibleguy.net/'
homepage: 'https://ansibleguy.net'
issues: 'https://github.com/ansibleguy/collection_opnsense/issues'
build_ignore: []
